github/elastomer-client

test/client/bulk_test.rb, test/client/cluster_test.rb, test/client/docs_test.rb, test/client/index_test.rb, test/test_helper.rb
Making sure everything works with ElasticSearch 1.4. Thus far it has only been test changes to support differences in response bodies from `aliases` methods and `mappings` methods.
/cc @grantr @dewski @shayfrendt
=> ES 1.4 updates

lib/elastomer/notifications.rb, lib/elastomer/version.rb, test/notifications_test.rb
I've found a need to access the response body in the notifications payload. I would like to measure the different between the request timing and the search time reported by ES in the response. The difference between the two timing values is the network latency.
/cc @grantr @dewski @shayfrendt
=> Response body in the notifications payload

.travis.yml, script/cibuild, test/client/repository_test.rb, test/client/snapshot_test.rb, test/test_helper.rb
On ES 1.6+ creation of FS repositories is impossible unless `repo.path` is set in the config. This causes snapshot and repository tests to fail with a default ES config, which is not great.
Instead of always running snapshot tests, only run them if repo creation succeeds. If repo creation fails, snapshot tests are skipped and a warning is displayed:
```
Could not create a snapshot repo. Snapshot tests will be disabled.
To enable snapshot tests, add a path.repo setting to your elasticsearch.yml file.
```
/cc @TwP
=> Run the snapshot tests only when repo creation is possible

Rakefile, script/test
Test files located directly under the `test/` folder were not being run. The matching patterns would only find test files located in sub-folders of the `test/` folder.
/cc @grantr
=> Fixing test file patterns

test/client/repository_test.rb, test/client/snapshot_test.rb
Cheating a little bit here and putting the `skip` statement in the `before` block so that we check if snapshots are possible with the current ES configuration. If not, then each test is skipped and a nice message is displayed to the user telling them how to enable these tests.
/cc @grantr
=> Skip individual tests

CHANGELOG.md, lib/elastomer/client/scroller.rb, lib/elastomer/version.rb, test/client/scroller_test.rb
This allows for other URL parameters (such as the query string in #106)
to be applied to a scroll operation.
I would like to hear feedback on the approach taken here (using an `@opts` instance variable to bundle the options together) and the code style.
=> Propagate original Scroller options

lib/elastomer/client/delete_by_query.rb, lib/elastomer/client/docs.rb, lib/elastomer/client/index.rb, test/client/index_test.rb
This breaks up the rather large delete_by_query method and puts it in its own class so that it's more manageable. Note that is a branch off of use-scroll-for-delete-by-query, not master.
Command objects are new to me, so this probably isn't the proper way to do it. Let me know if you have any feedback.
/cc @TwP @grantr
=> Translate the delete_by_query method into a command object

CHANGELOG.md, lib/elastomer/client/bulk.rb, lib/elastomer/client/delete_by_query.rb, lib/elastomer/version.rb, test/client/bulk_test.rb
This adds streaming bulk functionality via Ruby's Enumerators.
This does not to alter any of the existing methods in backwards incompatible ways so that a conversation about making the API more consistent could take place later. Because of that, some of the small operation methods had to be nearly duplicated.
This solves #92.
/cc @TwP @grantr
=> Streaming bulk operations

CHANGELOG.md, lib/elastomer/client/index.rb, lib/elastomer/client/warmer.rb
Since warmers require an index scope, we should be consistent and only provide access from an Index object. This is a breaking change.
/cc @TwP @chrismwendt
=> Remove Client#warmer method

test/client/delete_by_query_test.rb
Running the delete by query tests locally resulted in all documents in my local ES installation being deleted. The delete by query tests were scoped at the `$client` level, not at the `@index` level. So the scan / bulk delete operations iterated over all the indices in my development ES step :disappointed: 
These changes scope the tests to just the test index :smile:
/cc @chrismwendt @grantr
=> Scope the delete by query tests to a single index

lib/elastomer/client/delete_by_query.rb
This prevents the unused `_source` field of search results from being sent over the network.
Solves #117.
/cc @TwP @grantr
=> Omit source in delete_by_query searches

lib/elastomer/client/docs.rb, lib/elastomer/client/index.rb, lib/elastomer/client/multi_percolate.rb, lib/elastomer/client/percolator.rb, test/client/docs_test.rb, test/client/index_test.rb, test/client/multi_percolate_test.rb, test/client/percolator_test.rb
This looked like low hanging fruit, so I decided to give it a shot. "Percolate API" #24 is the motivating issue.
=> Implement the percolate API

test/client/nodes_test.rb, test/test_helper.rb
This makes the `hot_threads` test deterministic and increases the stability of other tests by increasing the `read_timeout`.
Fixes #120.
/cc @TwP @grantr
=> Make tests more stable

elastomer-client.gemspec
This updates to the latest Faraday branch. There are a handful of not-backwards-compatible changes in the 0.9.x series of the Faraday gem, but it doesn't seem like any of those changes affect this library.
=> Bump faraday dependency version

elastomer-client.gemspec
Reverts github/elastomer-client#116 - see discussion stemming from https://github.com/github/elastomer-client/pull/116#issuecomment-144756455.
=> Revert "Bump faraday dependency version"

lib/elastomer/client/index.rb, test/client/index_test.rb, test/test_helper.rb
This PR adds support for the [suggesters API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html) in Elasticsearch.
/cc @chrismwendt @grantr
=> Suggest endpoint

lib/elastomer/client/bulk.rb
I keep getting bit by a hanging process, only to find that I forgot to set the `request_size` when streaming bulk operations. This sets a default `request_size` of 10MB.
cc @github/search
=> Default bulk streaming request_size to 10MB

lib/elastomer/version.rb
This release of `elastomer-client` is now compatible with the ES 2.X main major version. The decision was made to sync up the client version number with the Elasticsearch version number - at least the major number. Hence the jump from 0.9.0 to 2.0.0
/cc @chrismwendt @grantr
=> Preparing release 2.0.0

lib/elastomer/client/delete_by_query.rb, test/client/delete_by_query_test.rb
This fixes delete by query when routing is required.
In ES 1.x, `_routing` is not required when deleting a document, and `_routing` is not returned in query results.
In ES 2.x, `_routing` is required when deleting a document if the mapping requires `_routing`, and `_routing` is returned in query results.
=> Fix delete by query with required routing

lib/elastomer/client.rb, lib/elastomer/client/bulk.rb, lib/elastomer/client/errors.rb, lib/elastomer/middleware/limit_size.rb, test/client/bulk_test.rb
The goal of this PR is to add some default request size limits to elastomer client. Currently with our `bulk` indexing layer, it is possible to send very very large requests to Elasticsearch - multi-gigabyte requests.
This PR implements a `limit_size` request middleware that will raise a `RequestSizeError` if the request body exceeds a a `max_request_size`. This limit defaults to 250 MB, but it is configurable when the `Elastomer::Client` is first created.
This PR also reworks the criteria determining when an actual bulk request is set. As bulk request actions are accumulated, we now perform a pre-check on the request size to ensure that a large document does not push any single bulk request above this request size. Any single document that is larger than the request size will also raise …
=> Enforce request size limits

lib/elastomer/client.rb, lib/elastomer/client/errors.rb, test/client/docs_test.rb, test/client/index_test.rb
This PR is aimed at adding some exception wrappers around common error responses from Elasticsearch. The problem is that in some of our error handling code we have lines like this:
```ruby
rescue StandardError => err
if err.message =~ %r/IndexMissingException|index_not_found_exception/
end
```
A better approach is to rescue a named exception and not worry about using a regular expression on the error message to figure out what the problem actually is.
/cc @chrismwendt @grantr
=> Exception wrapping

lib/elastomer/client.rb, test/client_test.rb
This prevents excon from [changing the encoding of the body](https://github.com/excon/excon/blob/v0.32.1/lib/excon/connection.rb#L183), causing downstream encoding compatibility errors.
Fixes #138
/cc @github/search
=> Freeze the body to prevent excon from changing its encoding

.travis.yml
- Adds a build matrix including both Elasticsearch 2 and 5
- The ES 5.6.4 build is marked as optional so we can fix test failures there without blocking merging
Closes #142.
=> Build against Elasticsearch 5.6 on Travis CI

lib/elastomer/middleware/encode_json.rb, test/middleware/encode_json_test.rb
If a `PUT` or `POST` request does not have a body, we still need to add a 'Content-Type' to the HTTP request headers. This change accounts for that condition.
This will clear up the warnings about missing 'Content-Type' that are being emitted by the `net/http` library.
/cc @look
=> Add 'Content-Type' for empty request bodies

test/client/docs_test.rb, test/client/percolator_test.rb
This PR cleans up some warnings that were being emitted during test runs. The tests are now clean on ES 2.4
=> Fix warnings

docs/notifications.md, lib/elastomer/client/docs.rb, lib/elastomer/client/index.rb, lib/elastomer/client/repository.rb, lib/elastomer/client/scroller.rb, lib/elastomer/client/snapshot.rb, test/client/cluster_test.rb, test/client/docs_test.rb, test/client/index_test.rb, test/client/nodes_test.rb, test/client/repository_test.rb, test/client/snapshot_test.rb, test/client/template_test.rb, test/notifications_test.rb, test/test_helper.rb
This PR removes all the Elasticsearch 1.X (and earlier) code paths from the client gem. We will no longer be supporting any versions of Elasticsearch prior to Elasticsearch 2.X.
=> Removing ES 1.X code paths

test/test_helper.rb
This adds an `ES_PORT` environment variable for tests that defaults to 9200 if
not present, so the behavior will not change if it's not set. However, having
this allows you to run multiple versions of Elasticsearch locally for testing.
To start a different version of Elasticsearch than your default, use:
bin/elasticsearch -E http.port=9400 -E transport.tcp.port=9500
Then start the tests with:
ES_PORT=9400 bin/rake test
Of course, you can use any port you like, but they must match, and you must set
the TCP transport port to be different than the default.
cc @elireisman
=> Make ES port configurable to support testing multiple versions

script/cibuild
If the Gemfile.lock WASN'T there, the build would fail. :(
This will ignore the error and allow the build to proceed.
=> Use rm -f on Gemfile.lock

.travis.yml
Doing multiple steps in the script phase was causing builds to not fail-fast if
Elasticsearch is not started.
However, the bigger problem is that...Elasticsearch wasn't started. I moved the
test for that to run after installing gems so it will have more time to start
up. I have not changed the wget arguments but I did use the long options so it's
easier to understand. If necessary we can increase --waitretry or --tries.
cc: @elireisman @TwP This is a CI-only change that should mitigate Travis CI failures, so I'm going to go ahead and merge it.
=> Move build prerequisites to install phase

elastomer-client.gemspec, test/client/bulk_test.rb
I couldn't find this in the changelogs or API docs, but experimentally ES 5
responds to a bulk "index" operation with no ID with a "index" response instead
of a "create" response.
This also adds awesome_print to help debug output during tests. When you need to
use it `require "awesome_print"` and then use `ap`.
@TwP I'm not sure how far you want to go in making this library look like ES 2. We could post-process the result of indexing operations to change the key in the response (maybe by detecting an "ES-like" ID?) but I'm not sure if that's worth it/desired.
cc: @elireisman
=> Handle difference in ES 5 bulk API behavior

lib/elastomer/client/errors.rb, lib/elastomer/client/warmer.rb, test/client/es_5_x_warmer_test.rb, test/client/warmer_test.rb
Warmers have been deprecated as of ES 2.3 and removed from Elasticsearch as of
5.0:
https://www.elastic.co/guide/en/elasticsearch/reference/2.3/indices-warmers.html
https://www.elastic.co/guide/en/elasticsearch/reference/5.0/indices-warmers.html
I have marked Elastomer::Client::Warmer as DEPRECATED and skipped the tests when
running under ES 5.x.
=> Deprecate warmers

test/client/index_test.rb
Use `payloads` conditionally as 5.x drops support for index-time payloads.
I did it this way to keep the old behavior but maybe we could just remove `payloads` altogether for both versions?
=> Use `payloads` conditionally for 5.x compatibility

test/client/index_test.rb
In Elasticsearch 2.x, requesting an alias that does not exist will return an
empty result. But in Elasticsearch 5.x, it will raise an error. This applies to
both full matches and wildcards.
This documents the difference, it doesn't do anything to paper it over.
cc: @juruen @elireisman
=> New assertions to document 2.x/5.x alias behavior

lib/elastomer/client.rb, lib/elastomer/client/warmer.rb, lib/elastomer/version_support.rb, test/client/bulk_test.rb, test/client/cluster_test.rb, test/client/docs_test.rb, test/client/es_5_x_warmer_test.rb, test/client/index_test.rb, test/client/multi_percolate_test.rb, test/client/multi_search_test.rb, test/client/scroller_test.rb, test/client/warmer_test.rb, test/core_ext/time_test.rb, test/test_helper.rb, test/version_support_test.rb
VersionSupport is pretty basic right now but the idea is to have a place to
stash version-aware helpers. Currently it's used to provide a way to paper over
the difference between `text` and `keyword` fields in ES 5+ and `string` fields
in ES 2.
Supposedly ES 5 can take a legacy `string` field and do the right thing with it,
but there are severe limitations, such as not being able to handle an a `string`
field with `term_vectors` enabled. :(
See: https://github.com/elastic/elasticsearch/issues/21356
I've used the VersionSupport helpers to update all the tests that were using `string` fields. With this in place I'm getting 3 failures and 42 errors.
**UPDATE:** After some discussion with @TwP I updated the tests to use intention-revealing names for their version checks as well. I think this …
=> Add VersionSupport class for ES version differences

test/client/docs_test.rb
`filter` was renamed to `post_filter` in 1.0(!) It has been removed in 5.0 so
this causes a test failure in the 5.x build.
=> Change test using deprecated `filter` API

test/notifications_test.rb
The notification tests were failing when using Elasticsearch run via a Docker container. The test was running too quickly and the shards for the test index had not yet been allocated. Using our `wait_for_index` helper ensures the index has been fully created so the tests will pass.
=> Fixing transient failure

CHANGELOG.md, docs/index.md, docs/notifications.md, lib/elastomer/client/index.rb, test/client/index_test.rb
This was deprecated in favor of `forcemerge` in 2.1:
https://www.elastic.co/guide/en/elasticsearch/reference/2.1/indices-optimize.html
A few options if we would want to break the API:
1. Use an `alias_method` for `optimize` that would use `forcemerge`. However, this wouldn't work with ES 2.0.x, i.e: 2.0, 2.0.1 and 2.0.2.
2. Use approach (1) but detect whether we are targeting ES 2.0.x to use `_optimize` instead.
3. Support both  `optimize` and `forcemerge` at the same time.
Update: we ended up taking  approach (1)
=> rename `Index#optimize` to `Index#forcemerge`

lib/elastomer/client/errors.rb, lib/elastomer/client/percolator.rb, lib/elastomer/version_support.rb, test/client/docs_test.rb, test/client/multi_percolate_test.rb, test/client/percolator_test.rb, test/test_helper.rb
I expect this will receive a few more updated to the PR and probably a couple more test cases but thought I would put this out for everyone to have a peek in the meantime.
- legacy `_percolate`, `_percolate/count` and `_mpercolate` API endpoints are deprecated but still function if percolation for the given index mapping is configured properly, and some perc queries are registered using the new API
- legacy `/:index/.percolate/:id` for registering perc q's on an index are gone in 5.x although docs claim ES5 can still read indices written by an older ES version
- However, types like `.percolator` starting with `.` aren't allowed anymore in 5.x
- an index that needs perc q's must register a new datatype for the queries in the index mapping, and that must have a field of type `percolator`
- …
=> Update Percolator APIs for ES 5.x upgrade

test/client/index_test.rb, test/test_helper.rb
The `output` option for fields (to be used as the output for suggest queries)
was removed in 5.0. I split up the suggestion tests so there is one specifically
testing this behavior change.
See: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/breaking_50_suggester.html#_simpler_completion_indexing
=> Handle ES 5 removing `output` option for fields

lib/elastomer/client/scroller.rb
Passing the scroll_id directly in the request body
without being wrapped in a json object makes
ES 5.X unable to parse it.
It seems that previous ES versions supported both a json object and just the id.
cc @look and @elireisman
=> pass scroll_id as a json object

lib/elastomer/client.rb, lib/elastomer/version_support.rb
ES 2.x uses query_parsing_exception and ES 5.x uses query_shard_exception or
parsing_exception depending on where the parse error occurs (top-level keys
error out early, but a query string parse failure will happen on a shard and
throw a different exception).
Java classes:
https://github.com/elastic/elasticsearch/blob/v2.4.6/core/src/main/java/org/elasticsearch/index/query/QueryParsingException.java
https://github.com/elastic/elasticsearch/blob/v5.0.0-alpha1/core/src/main/java/org/elasticsearch/index/query/QueryShardException.java
https://github.com/elastic/elasticsearch/blob/v5.0.0-alpha1/core/src/main/java/org/elasticsearch/common/ParsingException.java
I also removed an ES 1.x code path that is unnecessary now.
=> Handle different query parsing exception between versions

lib/elastomer/client/index.rb, test/client/index_test.rb
In ES 5.x, it's required to pass the analyzer as
a json object in the body and not as a URI parameter.
This PR does so by passing all the parameters bar `:index` in the body.
\cc @look and @elireisman
=> pass analyzer as a json object

lib/elastomer/client/delete_by_query.rb, lib/elastomer/client/scroller.rb, test/client/scroller_test.rb
This is my first attempt at fixing the deprecated `scan` search_type in 5.x.
First of all, this depends on another super simple PR https://github.com/github/elastomer-client/pull/162 that fixes how `scroll_id` is passed.
The recommended way to replace the `scan` functionality according to the ES doc https://www.elastic.co/guide/en/elasticsearch/reference/2.1/breaking_21_search_changes.html#_literal_search_type_scan_literal_deprecated is to do the following:
>search_type=scan deprecatededit
The scan search type has been deprecated. All benefits from this search type can now be achieved by doing a scroll request that sorts documents in _doc order, for instance:
```
GET /my_index/_search?scroll=2m
{
"sort": [
"_doc"
]
}
```
We do so in the query that we send to ES.
The other thing that we …
=> Implement scan through scroll plus sort by doc (fixes delete_by_query in 5.x)

.gitignore, CHANGELOG.md, lib/elastomer/client/multi_percolate.rb, test/client/index_test.rb, test/client/multi_percolate_test.rb
A subset of multi_percolate tests in `index_tests.rb` that exercises the block form of bulk percolation still had an error. Exploration with `byebug` and `awesome_print` revealed that params weren't populating the final request body in the same way they did with the full-body tests or my tests of the legacy `_mpercolate` APIs that worked on 2.4 and 5.6 locally.
This PR updates all that stuff.
=> Update multi_percolate tests

lib/elastomer/client/delete_by_query.rb, lib/elastomer/version_support.rb, test/client/scroller_test.rb, test/test_helper.rb, test/version_support_test.rb
The change here allows `index` and `type` to be passed to the scroll query. These parameters are used to restrict the `delete_by_query` action to the given index and document type.
=> Fix the `delete_by_query` logic

lib/elastomer/client/docs.rb, lib/elastomer/client/errors.rb, lib/elastomer/version_support.rb, test/client/docs_test.rb, test/test_helper.rb, test/version_support_test.rb
Pull the different "special" fields that affect indexing into VersionSupport in
order to return a different Hash of parameter name/field name depending on the
client's version.
If a caller attempts to index a document with a known indexing directive field
that is not supported by the version of Elasticsearch, the client will fail fast
and not allow the document to be indexed.
Fixes #178.
=> Fail fast on known invalid indexing directive fields

lib/elastomer/client.rb, lib/elastomer/client/docs.rb, lib/elastomer/client/errors.rb, test/client/docs_test.rb, test/client/errors_test.rb, test/test_helper.rb
With Elasticsearch 5.X now validating the parameters passed with each HTTP request, this code raises an InvalidParameter excpetion if we violate what Elasticsearch expects. This will help us find and fix these problems in our own application.
=> Raise an IllegalArgument exception

lib/elastomer/client.rb, test/client_test.rb
The goal of this PR is to implement an `Elastomer::Client#dup` method that returns a client with the same configuration but with a unique connection to the Elasticsearch cluster. This is useful for multi-threaded environments where the socket connection to the cluster should not be shared across thread boundaries.
=> Implement `dup` method for Client

lib/elastomer/client.rb, lib/elastomer/notifications.rb, script/cibuild, test/client_test.rb
The goal of this PR is to add automated retries for failed requests. A new attribute `max_retries` is added to the client. This determines the maximum number of retry attempts that will be made by the client; it can be overridden on a per-request basis.
Only `GET` and `HEAD` requests can be retried. My thought here is that `PUT`, `POST`, and `DELETE` requests might actually succeed on the Elasticsearch cluster, but the request itself might timeout. In this case the desired modification was made so we do not want to retry the request.
Only a handful of exceptions can be retried. See:
https://github.com/github/elastomer-client/blob/master/lib/elastomer/client/errors.rb#L91-L95
=> Retry requests when possible

lib/elastomer/version_support.rb
just quick shim for updating the `lib/elastomer/indexes` `:norms` and any other stray fields that should be on strict boolean values now
=> add version_support shim for strict bool fields

lib/elastomer/client/app_delete_by_query.rb, lib/elastomer/client/scroller.rb
The main object of this pull request is to allow the passing of the `routing` parameter to the application `delete_by_query` implementation. The approach I took was to remove the param validations since the implementation is focused primarily on ES 2.X where parameter validation is not enforced. If ES 5.X or higher is being used, then the native `delete_by_query` implementation is used by default.
=> Allow routing for delete_by_query

lib/elastomer/client/scroller.rb
The change here ensures that the scroll context is cleared when no more results are returned from the scroller. This applies to `scan` queries which are implemented via the `Scroller`.
=> Always clear the scroll context

lib/elastomer/version_support.rb, test/version_support_test.rb
as title suggests. Shims the param lists we use for validity checks across versions, also provides a shim method for use by callers during upgrade transition.
=> Handle op_type compatibility in VersionSupport

lib/elastomer/version_support.rb
for caller-side shims removing illegal unexpected req params when talking to ES5+ needed for `:read_timeout` for `native_delete_by_query`, `:timeout` for `_count` and `_refresh` params, and others (gh/gh PR for this on the way once this is checked in)
=> alias for strict request params by ES version

lib/elastomer/client/docs.rb, lib/elastomer/version_support.rb, test/version_support_test.rb
This removes parameter validation code from the `Docs` module and relies on the `ApiSpec` validations that we now have in the client request method.
=> Parameter validation cleanup

docker/docker-compose.cibuild.yml, lib/elastomer/middleware/opaque_id.rb
To help debug Opaque ID exceptions, this PR includes the request and response UUIDs in the exception message raised when conflicting Opaque IDs are detected.
=> Show conflicting opaque IDs in exception message

elastomer-client.gemspec, lib/elastomer/client.rb
Add Faraday::Middleware::Gzip to the client to request compressed responses from
Elasticsearch if it is configured to allow that.
This should improve network transfer time at the cost of CPU on the client and
server.
=> Request compressed responses from Elasticsearch

lib/elastomer/client.rb, lib/elastomer/middleware/compress.rb, lib/elastomer/version_support.rb, test/client_test.rb, test/test_helper.rb
This unconditionally compresses request bodies for requests to ES 5.x servers.
Some thoughts about this code:
* ~Since this is a configurable behavior in ES, it'd probably be better to pass in whether or not you want compression as a flag to the client.~ UPDATE: I have made this change.
* ~It probably makes sense to only compress request bodies over a certain size. Thoughts on what that should be?~ UPDATE: I used roughly the MTU for an Ethernet packet (1500 bytes, I went with 1400).
* ~The compression level is `Zlib::DEFAULT_COMPRESSION` which is level 6. If we're worried about CPU we may want to compress at level 1. Or we could make this configurable, too so we can experiment.~ UPDATE: This is now configurable.
=> Compress request bodies

lib/elastomer/client.rb, lib/elastomer/client/errors.rb, test/client/errors_test.rb, test/client_test.rb
This pull requests adds a custom `RequestError` subclass for `es_rejected_execution_exception` exceptions.
This error is marked as non-fatal.
* https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/common/util/concurrent/EsRejectedExecutionException.java
* https://aws.amazon.com/premiumsupport/knowledge-center/resolve-429-error-es/
=> Add custom non-fatal error for rejected execution exceptions

lib/elastomer/client.rb, lib/elastomer/client/errors.rb, test/client/docs_test.rb, test/client/errors_test.rb
This PR adds a new type of `Elastomer::Errors::RequestError` called `Elastomer::Errors:: DocumentAlreadyExistsError` for when duplicate documents are indexed when `op_type: "create"` is passed along with the document to be indexed.
/cc @elireisman
=> Add DocumentAlreadyExistsError exception

CHANGELOG.md, lib/elastomer/version.rb
Hi! this is to bump the version and add a 3.1.5 tag as a prereq to releasing the new RubyGems version 🎉 
I am still battling some problems with my local env that I'm going to ask about in #friction (feel free to drop ideas here if this rings a bell) before I push the release, as I can't even run the test suite locally right now.
=> Bump Elastomer-Client to v3.1.5

.travis.yml, README.md, elastomer-client.gemspec, script/bootstrap
- Bump the bundler version
- Update the bootstrap `cd` line to use `dirname "$0:a"` which is compatible with both zsh and bash
- make sure to specify `bundle exec` for running tests
=> Bundler version bump and updated bootstrap script

lib/elastomer/client.rb, test/client_test.rb
- Overrides `Elastomer::Client#inspect` to hide `basic_auth` and `token_auth` params from console output
Depends on #214 
Fixes #212
=> Filter basic_auth and token_auth params on client inspection

elastomer-client.gemspec, lib/elastomer/client.rb, test/client_test.rb
- Adds ability to trigger basic_auth or token_auth on client connections
- Specify `basic_auth: { username: "myusername", password: "mypassword" }` in new client params to trigger basic auth
- Specify `token_auth: "mytoken"` in new client params to trigger token auth
- Overrides `Elastomer::Client#inspect` to hide `basic_auth` and `token_auth` params from console output
- Silences some noisy instance variables on inspection
Fixes #207 
Fixes #211
Fixes #212
=> Add config based basic and token auth to Elastomer::Client#connection

CHANGELOG.md, elastomer-client.gemspec, lib/elastomer/version.rb
=> Bump Webmock version to support Ruby 2.6

test/client/bulk_test.rb
This isn't a blocker, but I happened to notice it as I was preparing to fix
some Ruby 2.7 warnings.
=> Delete unused variable in test

lib/elastomer/client/rest_api_spec/rest_api.rb
In Ruby 2.7 passing a Hash to a method that is expecting keyword arguments triggers
a warning.
The `url` value is a Hash here.
=> Use kwargs explicitly in call to Url.new

lib/elastomer/client/scroller.rb
A very tiny documentation change: reponse -> response
=> Fix typo in comment

.github/workflows/main.yml, elastomer-client.gemspec, lib/elastomer/notifications.rb, script/bootstrap, test/client/bulk_test.rb, test/client/repository_test.rb, test/client_test.rb, test/middleware/opaque_id_test.rb, test/test_helper.rb
In preparation for new work on this library, ensure it works with supported versions of Ruby (2.7, 3.0, 3.1) and drop unsupported versions (< 2.7).
Notes:
- Swap out `pry-byebug` for `debug` gem for better debugging
- Add `require "active_support"` to `notifications.rb` to resolve error with `uninitialized constant ActiveSupport::IsolatedExecutionState`
- Update `bootstrap` file to remove deprecation warnings
- Use `**` operator to pass hashes as keyword arguments (due to change in Ruby 3)
- Use Minitest `_` [method](https://www.rubydoc.info/gems/minitest/Minitest/Spec/DSL/InstanceMethods#_-instance_method) to remove deprecated global use of `must_raise`
=> Upgrade Ruby versions supported by library

docker/docker-compose.es24.yml, docker/docker-compose.es56.yml, docs/client.md, docs/cluster.md, docs/docs.md, docs/index.md, docs/notifications.md, script/cibuild
Change the port used to run ES locally from 19200 to 9200, which is the default. That makes it easier to run tests and develop locally without having to override the port (e.g., with `ES_PORT`).
**Notes:**
- change in the Docker files
- remove the client.md section on Boxen (no longer used) which talks about running it on 19200
- update anywhere 19200 was used in docs
=> Change port to use default of 9200

.gitignore, lib/elastomer/client/rest_api_spec/api_spec.rb, lib/elastomer/client/rest_api_spec/api_spec_v7_17.rb, lib/elastomer/version_support.rb, script/generate-rest-api-spec, test/client/tasks_test.rb, test/test_helper.rb, test/version_support_test.rb
Get a basic ApiSpec for ES 7 generated via the `script/generate-rest-api-spec` script.
Initially I tried to rework the ApiSpec class to fit the new data structure of the ES 7 JSON API files (where `methods` and `parts` are under each `path` object). Instead, the ES 7 schema was fit into the existing ApiSpec class, which was slightly quicker. That will allow us to start making progress on getting the tests to run against ES 7 while refactoring the ApiSpec schema alongside the test work.
**Notes:**
- `es_version_5_x?` was renamed to `es_version_5_plus?` with the idea that changes introduced into ES5 are likely present in higher versions (e.g., compared with ES2)
- a new `es_version_7_plus?` method was added along the same lines
- params in ERB.new call were updated to remove deprecation …
=> Generate initial ApiSpec for ES 7

test/assertions.rb, test/client/index_test.rb, test/client/multi_search_test.rb
Found a few breaking changes here:
- `_percolate` and `_mpercolate` endpoints removed: https://www.elastic.co/guide/en/elasticsearch/reference/6.8/breaking-changes-6.0.html#breaking_60_percolator_changes
- `_suggest` endpoint removed: https://www.elastic.co/guide/en/elasticsearch/reference/5.4/search-suggesters.html
I also added a test for the term suggester to multi_search_test.rb using [this documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/search-suggesters.html) for reference.
- Using wildcards to get aliases does not raise an error if no match is found. I did not find any documentation for this, but I found documentation on similar behavior for other endpoints - https://www.elastic.co/guide/en/elasticsearch/reference/6.8/breaking-changes-6.0.html#_open_close_ …
=> Fix index_test.rb for ES 7

lib/elastomer/client/docs.rb, test/client/docs_test.rb, test/client/multi_percolate_test.rb, test/client/percolator_test.rb
This PR fixes tests for docs on ES 7.
I also added changes to skip percolator and multi percolator tests for ES 7, since those endpoints were removed ES 6 onwards and adding new tests will need more changes, and we don't use the percolator endpoints on dotcom.
=> [ES7 upgrade] Fix docs tests and skip percolator and multi percolator tests

lib/elastomer/client.rb, lib/elastomer/client/bulk.rb, test/assertions.rb, test/client/app_delete_by_query_test.rb, test/client/native_delete_by_query_test.rb, test/client/scroller_test.rb, test/client/snapshot_test.rb, test/client/template_test.rb
This PR fixes scroller, snapshot, template, delete by query tests for ES 7. 
Once this PR merges, all tests should pass for ES 7.
Notes:
- While fixing the native_delete_by_query tests, I found that the default `number_of_shards` for an index in ES 7 is 1, while in ES 5 it was 5. Since ES 7 was only creating 1 shard, deleting by specifying `_routing` values did not work because all the documents were in the same shard ([link to documentation for _routing](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/mapping-routing-field.html)). I also noticed that the calculation of the shard number for each document we index has changed in ES 7:
ES 7:
ES 5:
I am not sure if and how this routing change in ES 7 affects github/github, but thought it was worth noting.
- app_delete_by_query …
=> [ES 7 upgrade] Fix scroller, snapshot, template, delete by query tests

.github/workflows/main.yml, .overcommit.yml
Now that the existing test suite passes against ES 7, add ES 7 to the CI workflow.
Additionally, ES 2.4.6 was removed from the matrix. The `run: "sed...` line was not compatible with ES 7. While a conditional could be added, support for ES 2 is going away soon so it's simpler to remove that line and version.
The workflow also now uses Actions cache for the unzipped ES 2 and ES 5 binaries. This change speeds up the workflow runs and saves bandwidth by skipping the download step. According to the [Actions documentation](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key), feature branches should use the cache of the default branch, which can be verified once this PR is merged. 
Screenshot of skipping the download step:
One …
=> Add ES 7 to the CI workflow

lib/elastomer/client/docs.rb, test/client/docs_test.rb
ES 5 has a type param for all endpoints, while ES 7 does not accept the type param. For ES 7 document APIs, the commonly used endpoints - index, get, delete, exists - need to have an `_doc` in the path. So removing type will not work for document APIs.
Because of this, I decided to add the type param and set it to `_doc`, since this ensures that all the endpoints work as expected. 
To test this change, I added an additional test, which calls all the docs endpoints that we use in dotcom (index, get, update, multi_get, delete, exists, count, search) with a type param.
=> [ES7 upgrade] Make document APIs work even when type is passed for ES7

lib/elastomer/client/bulk.rb, lib/elastomer/client/index.rb, test/client/index_test.rb
For the index APIs, only 3 endpoints have a type param in ES5 - `exists_type`, `get_mapping` and `put_mapping`. These 3 endpoints have an optional type param in ES7, and if you want to pass the type param, you have to also set `include_type_param` to true. `include_type_param` is deprecated in ES7, and removed from ES8. So I thought it would be better to not use the type param at all for ES7, so I removed the type param from all ES7 index API requests. After these changes, if you do pass a type param to ES7, it will be removed before calling the actual index endpoint.
The test I added checks for `get_mapping` and `update_mapping` only. `exists_type` is deprecated in ES7 and removed from 8. We don't expose that endpoint, and I didn't find any usage of this in dotcom, so I did not add a …
=> [ES7 upgrade] Allow passing type param for Index APIs

lib/elastomer/client/docs.rb, lib/elastomer/client/scroller.rb, test/client/template_test.rb
Fix the remaining test failures for ES 8. For the scroller and multi_search tests, the issue was similar to the one mentioned in #246, which is that the `type` param is no longer allowed for certain endpoints.
For the template test, the issue is that for [legacy index templates](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/indices-templates.html), ES 8 now enforces the change from a string `template` parameter to a list of strings named `index_params` ([8.6 doc](https://www.elastic.co/guide/en/elasticsearch/reference/8.6/indices-templates-v1.html)). The test includes ES 7 since the `template` param was deprecated in that version.
=> Fix remaining failing tests for ES 8

.github/workflows/main.yml
This PR adds ES 8 to the CI workflow.
Additionally:
- removes Ruby 2.7 - it will be EOL in about 2 months, so keep the CI process smaller
- removes the "Install dependencies (Ubuntu)" step - shortens build time, as updating isn't necessary, and installing a Java 8 JRE isn't needed (or wanted). ES comes bundled with more modern JREs.
- disables HTTPS for ES 8 (and 7). The command line option doesn't work with the ES 5 binary, so there's a conditional for that step.
=> Update CI for ES 8

lib/elastomer/version_support.rb
This PR cleans up the version_support.rb file by removing a few comments and an unused method noticed during a final review of the changes before release. It also bumps the supported version to `< 9.0`. It's reasonable to expect the library to continue working without modification through the 8.x minor releases.
=> Cleanup version_support.rb

CHANGELOG.md, README.md, docs/client.md, docs/cluster.md, docs/docs.md, lib/elastomer/version.rb
This PR bumps the version to 4.0.0 and updates the CHANGELOG with latest high-level work.
=> Prepare for 4.0 release

lib/elastomer/client/bulk.rb
Update bulk method to remove `$client` call for `version_support`
`$client` is only available in test methods, and `version_support` is available to call directly on the `bulk` method due to reopening the `Client` class
=> Fix version_support check in bulk class

lib/elastomer/version.rb
Update `Elastomer` version to `4.0.1` in order to release a new tag
=> Update version to 4.0.1

lib/elastomer/client/bulk.rb, test/client/bulk_test.rb
Closes https://github.com/github/elastomer-client/issues/256.
As per [these docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/breaking-changes-7.0.html#_camel_case_and_underscore_parameters_deprecated_in_6_x_have_been_removed), as of ES 7 certain params  (e.g. `_routing`) should be passed to the ES Bulk API without the underscore prefix. This ensures that we don't add the underscore prefix to just those params.
- I refactored the special key handling to make it a bit easier to follow (previously, the variable names were very terse, and it was difficult to understand the distinction between key and value in `SPECIAL_KEYS_HASH`). Now the logic is driven by two arrays, and we prefix the values of those arrays just-in-time when necessary.
- I stopped adding an underscore …
=> Do not prefix certain params passed to the Bulk API with underscores.

CHANGELOG.md, lib/elastomer/version.rb
This bumps the version of this gem to `4.0.2` in order to package the fix for #256.
I have tested that the new version of the gem works properly in a local environment as per https://github.com/github/elastomer-client#releasing.
=> Bump to version 4.0.2.

lib/elastomer/client.rb, test/client_test.rb
Fixes #261 
Instead of overriding the existing query_values, the new values are now merged in.
Before merging in, keys will be converted to strings to override existing values instead of appending. Otherwise the following would happen:
```ruby
expand_path("/my/path?param=1", param: "2") # => "/my/path?param=1&param=2"
expand_path("/my/path?param=1", "param" => "2") # => "/my/path?param=2"
```
Now it is consistent and both versions will give `"/my/path?param=2"`
=> Merge old and new query_values

lib/elastomer/client/docs.rb, lib/elastomer/client/index.rb, lib/elastomer/client/update_by_query.rb, test/client/docs_test.rb, test/client/index_test.rb, test/client/update_by_query_test.rb
Fixes #263 
This PR adds support for `_update_by_query`. 
I followed the implementation for `_delete_by_query`, but I didn't use the `native_` part. Seemed like some kind of backwards compatibility thing and just makes the interface longer?
=> Add update_by_query

test/client/index_test.rb
#264 still had a focus in the code when I merged it.
=> Remove focus from test

CHANGELOG.md, lib/elastomer/version.rb
This bumps the version of the gem to `4.0.3`
There is still an outstanding cleanup in #265, so this should be merged after that gets merged.
I followed the steps in the release section of the README to verify version is updated and new functionality works as expected by recreating a test with manual steps / without helpers.
=> Bump to version 4.0.3

CHANGELOG.md, lib/elastomer_client/client/bulk.rb, lib/elastomer_client/version.rb, test/client/bulk_test.rb, test/client/docs_test.rb
This PR intends to fix two different issues: 
1. For ES 7+ compatibility, the Bulk API will no longer send the `_type` parameter if the version is 7+. 
[Link to ES documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html) showing that `_type` is not a parameter for any of the bulk requests
As part of this change, all the bulk tests using this call have been updated to remove the `document_wrapper` helper method to test that the ES 5 requests still work correctly on ES 7+. The Docs API already has been doing this, so I was able to update the docs tests to remove the `document_wrapper` and confirm that all the tests still run properly. 
2. Fixes a small bug where string params were not being removed properly if the parameter was empty or nil. 
I added a …
=> Update bulk API to remove _type if version is > 7

lib/elastomer_client/client/rest_api_spec/api_spec_v8_7.rb
It looks like we're missing the spec for 8.7, so I get ahead and generated it via `script/generate-rest-api-spec 8.7`.
=> Add generated api spec for version 8.7

CHANGELOG.md, lib/elastomer_client/version.rb
Updates the version in `elastomer-client` to 5.0.2 and adds changes to CHANGELOG.
=> Update version of elastomer-client to 5.0.2

CHANGELOG.md, lib/elastomer_client/client/bulk.rb, lib/elastomer_client/version.rb, test/client/bulk_test.rb
Related to https://github.com/github/elastomer-client/pull/257
As per [these docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/breaking-changes-7.0.html#_camel_case_and_underscore_parameters_deprecated_in_6_x_have_been_removed), as of ES 7 certain params (e.g. _routing) should be passed to the ES Bulk API without the underscore prefix. The previous PR linked above handled that for parameters explicitly passed to the Bulk request. However, we also pass these parameters with some documents that are then converted to bulk parameters in the `from_document` method.
This PR updates the `from_document` method to handle underscored parameters being passed through the document for ES7+. 
I've added logic to fix this for when the parameter is passed as underscore, and when the …
=> Fix document parameters passed to bulk API when prefixed with underscores

lib/elastomer_client/client/bulk.rb, lib/elastomer_client/client/docs.rb
Both `timestamp` and `ttl` are deprecated indexing fields, as found in these [ES 5.0 breaking changes documents](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/breaking_50_mapping_changes.html#_literal__timestamp_literal_and_literal__ttl_literal).  
I removed these from the `SPECIAL_KEYS` array, as they are [removed in ES 6.0 ](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/breaking-changes-6.0.html#_literal_timestamp_literal_and_literal_ttl_literal_in_index_requests).
=> Remove timestamp and ttl deprecated parameter keys

CHANGELOG.md, lib/elastomer_client/version.rb
Update CHANGELOG and version for last changes from this [PR](https://github.com/github/elastomer-client/pull/273)
=> Update CHANGELOG and version to 5.0.4

lib/elastomer_client/client/bulk.rb, test/client/docs_test.rb
The "found" field was removed from the delete API response ES6 onwards.
We were only using the field for assertions in 2 tests. The other usages of found in the tests are for the get API, which still has the "found" field in responses for ES8.
There was also a sample delete API response in the bulk.rb file. I added a sample response for ES8 too, to reflect the "found" field being removed from the response.
=> Replace usage of "found" field by "result" in tests for the delete API

test/test_helper.rb
Tests and CI are failing due to the latest version of `minitest` removing an old compatibility layer, which was allowing "MiniTest" (capital T) to be used where "Minitest" (lowercase T) should have been used. This codebase does not need that layer, so a simple rename fixes all the tests.
From https://github.com/minitest/minitest/blob/master/History.rdoc#5190--2023-07-26-
> Only load minitest/unit (aka ancient MiniTest compatibility layer) if [ENV](https://github.com/minitest/minitest/blob/master/%22MT_COMPAT%22)
=> Rename MiniTest to Minitest

lib/elastomer_client/client.rb
Add the `@connection` instance variable to the list of noisy ivars so that it will not be output during calls to `inspect`. The amount of information is quite large and is mostly not helpful during debugging. The information is still available by other means, but removing it from the default output will make debugging clearer.
=> Reduce the noise of the client during an inspect call by hiding connection info

CHANGELOG.md, lib/elastomer_client/version.rb
Update library version to 5.0.5 and fix the formatting in CHANGELOG
=> Update CHANGELOG and version to 5.0.5

lib/elastomer_client/client/bulk.rb
This PR handles 2 bugs
1. Adds an additional check to prevent `type` from being used as a special key in ES8. `type` is allowed to be a normal field in ES8, and should not be converted to anything else.
2. As per [these docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/breaking-changes-7.0.html#_camel_case_and_underscore_parameters_deprecated_in_6_x_have_been_removed), as of ES 7, certain params (e.g. _routing) should be passed to the ES Bulk API without the underscore prefix. This PR updates `convert_special_keys` method to check for the prefixed keys as well as the non-prefixed keys in the parameters, and converts it to the correct key based on the version of ES.
=> Update convert_special_keys to properly handle ES8 unprefixed keys

CHANGELOG.md, lib/elastomer_client/client.rb, lib/elastomer_client/version.rb, test/client_test.rb
Allow custom configuration of the client's Faraday connection by passing a block to the client's constructor.
Bumped minor version and updated the changelog.
=> Allow a custom Faraday connection configuration block.

lib/elastomer_client/client.rb, test/client_test.rb, test/mock_response.rb
This PR moves the call to the opaque ID middleware to the end of the Faraday middleware chain. Currently the opaque ID middleware is being triggered earlier in the middleware stack and is wrapping the invocation of the other middleware in the chain after it.
This change will ensure that we can use middleware like circuit breakers without causing issues for the opaque ID middleware. So any time we short circuit the remote request, the opaque ID middleware will not be called.
=> Move opaque id to the end of the middleware chain

lib/elastomer_client/middleware/opaque_id.rb, test/client_test.rb
Currently, if ES returns a 500 response, we get an `OpaqueIDError` (and not the `ServerError`) since we only [check for an opaque ID mismatch](https://github.com/github/elastomer-client/blob/main/lib/elastomer_client/middleware/opaque_id.rb#L38) and don't handle the case when opaque ID is nil.
Here I added a check so that the `OpaqueIDError` will not be thrown if there is a 5xx response from Elasticsearch, and we will get a `ElastomerClient::Client::ServerError` instead.
=> Change opaque ID middleware to not throw OpaqueIDError on 5xx responses

.github/workflows/main.yml, docker/compose.yaml
Update CI to the same patch level we're planning to use throughout.
The .2 patch includes the fix for 8.13 that downgrades the JDK. More info:
https://www.elastic.co/blog/elastic-stack-8-13-2-released
=> Update CI to 8.13.2

elastomer-client.gemspec
This unlocks [faraday middleware gem](https://github.com/lostisland/faraday_middleware?tab=readme-ov-file) version so that it can be upgraded
=> Unlock faraday middleware gem version

CHANGELOG.md, elastomer-client.gemspec, lib/elastomer_client/client.rb, lib/elastomer_client/client/errors.rb, lib/elastomer_client/middleware/parse_json.rb, lib/elastomer_client/version.rb, test/client/errors_test.rb, test/middleware/parse_json_test.rb, test/notifications_test.rb
- Replace `Faraday::Error::*` with `Faraday::*` error classes (following the [upgrade guide](https://github.com/lostisland/faraday/blob/main/UPGRADING.md#errors))
- Handle all `Faraday::Error` instead of `Faraday::Error::ClientError`
- Unlock faraday version to allow 1.0.0
- Bumped up the faraday and faraday middleware gems slightly
=> Replace Faraday::Error::* usage

CHANGELOG.md, elastomer-client.gemspec, lib/elastomer_client/version.rb, test/client_test.rb
This is a followup to https://github.com/github/elastomer-client/pull/309
We can't upgrade faraday to 1.x without also upgrading faraday_middleware to 1.x, so the previous PR didn't get us all the way there.
Not much changes in faraday_middleware 1.x except for faraday 1.x support, so I expect elastomer-client to be fully compatible.
(We'll revisit this once more for faraday 2.0, which drops the faraday_middleware gem entirely, but that's a problem for another day.)
=> Unlock faraday_middleware version

CHANGELOG.md, lib/elastomer_client/client/reindex.rb, lib/elastomer_client/version.rb, test/client/reindex_test.rb
For native reindexing, it will be important to be able to throttle reindex operations incase they become too expensive. This PR adds support for that to elastomer-client. A subsequent PR will add it to the elastomer reindex framework
=> add rethrottle support to reindex api

README.md, docker/compose.yaml, docker/elasticsearch-follow.yml, script/setup-ccr
- Add docker compose profile for setting up a leader and follower ES clusters
- Add script to apply non-prod license to both clusters and setup remote connection
Next steps will be adding API support for ccr and testing it with this setup
=> Add Support for Configuring CCR Setup

lib/elastomer_client/client/reindex.rb
removes 2 redundant inclusions of params in a params.merge() call in reindex.rb
** There are 2 failing tests that also fail on the main branch, unrelated to this change
```
1) Failure:
ElastomerClient::Client::Snapshot#test_0005_gets snapshot status for one and all [test/client/snapshot_test.rb:73]:
Expected: 1
Actual: 2
2) Failure:
ElastomerClient::Client::Snapshot#test_0003_creates snapshots with options [test/client/snapshot_test.rb:51]:
--- expected
+++ actual
@@ -1 +1 @@
-["elastomer-snapshot-test-index"]
+[".tasks", "elastomer-snapshot-test-index"]
```
=> Removing redundant params in params.merge()

README.md, lib/elastomer_client/client/ccr.rb, script/setup-ccr, test/client/ccr_test.rb, test/test_helper.rb
- Add support for following an index
- Update test framework to support CCR
- will skip CCR tests if the replica isn't reachable
- Update readme
=> Add support for PUT _ccr/follow

.github/workflows/main.yml, README.md, docker/compose.yaml, lib/elastomer_client/client/rest_api_spec/api_spec_v8_18.rb, script/generate-rest-api-spec, script/setup-ccr, test/client/cluster_test.rb
This PR adds the Elasticsearch 8.18 specification to the project and changes references from 8.13.2 to 8.18.0
=> Elastic 8.18 Spec
