- .travis.yml
- test/test_helper.rb
Should be much faster than the old way:
http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
> Use containers on Travis

- .travis.yml
- README.md
- docs/client.md
- docs/docs.md
- docs/notifications.md
- lib/elastomer/client/docs.rb
- lib/elastomer/client/errors.rb
- lib/elastomer/client/index.rb
- lib/elastomer/client/multi_search.rb
- lib/elastomer/client/scroller.rb
- test/client/bulk_test.rb
- test/client/cluster_test.rb
- test/client/delete_by_query_test.rb
- test/client/docs_test.rb
- test/client/errors_test.rb
- test/client/index_test.rb
- test/client/multi_search_test.rb
- test/client/percolator_test.rb
- test/client/repository_test.rb
- test/client/template_test.rb
- test/client/warmer_test.rb
- test/client_test.rb
- test/test_helper.rb
This is a work in progress pull request to bring Elasticsearch 2.X compatibility to the elastomer-client codebase. The plan is to work through all the failing tests and iteratively fix issues until all the tests are green.
/cc @chrismwendt
> [WIP] ES 2.X Compatibility

- README.md
- script/cibuild
- script/test
There is no `testrb` in this repository so `script/test` does not work as
advertised. `rake test` is the current thing to use.
> Update instructions for running tests and fix Janky build

- .travis.yml
- README.md
- Install Elasticsearch 2.3.5 manually in the container-based test run time
- Wait for ES to start
- Run tests
> Attempt to fix Travis build

- lib/elastomer/client/cluster.rb
- lib/elastomer/client/index.rb
- test/client/cluster_test.rb
- test/client_test.rb
- test/notifications_test.rb
- test/test_helper.rb
These are just a few small fixes to start getting out test suite working with Elasticsearch 5. That is all ... not too much else to see here.
> Small fixes for ES5 compatibility

- CHANGELOG.md
- lib/elastomer/version.rb
Once this is approved, I'll merge and tag the release.
> Bump version to 2.3.0

- lib/elastomer/client.rb
- test/test_helper.rb
shorten method name, whitespace fix, use cheaper version call/string comp internally for checks
>  misc tweaks

- elastomer-client.gemspec
- test/test_helper.rb
With minitest-focus you can run a single test:
```
focus
it "is failing for some reason" do
...
end
```
With pry-byebug you can get an interactive debugger. I use it during test runs.
```
... code ...
binding.pry
... code ...
```
When `binding.pry` is reached, the interpreter will stop and drop you in a REPL.
> Add minitest-focus and pry-byebug to help with debugging

- docker/docker-compose.es56.yml
- script/cibuild
These are cosmetic changes to the output of the cibuild script so that it looks nicer in the janky environment. Also disabling more X-Pack features in the ES 5.6 Docker image.
> CI build environment tweaks

- .travis.yml
> Remove allowed failures from ES 5.X Travis CI builds

- lib/elastomer/version_support.rb
Oops, I used a method defined in test_helper.rb in this class. So of course all
the tests passed, but when I tried to use it in real code... 💣💥
> Don't use test helper methods in production code

- CHANGELOG.md
- lib/elastomer/version.rb
> Bump version to 3.0.0 and update CHANGELOG

- CHANGELOG.md
- lib/elastomer/middleware/opaque_id.rb
- lib/elastomer/version.rb
- test/middleware/opaque_id_test.rb
Bumping the version number of the gem in preparation for a release.
> Version bump for next release

- CHANGELOG.md
- README.md
- lib/elastomer/version.rb
Prep for release 3.2.0 (2019-08-22)
- Add config based basic and token auth to `Elastomer::Client#connection`
- Filter `Elastomer::Client#inspect` output to hide basic and token auth info,
and reduce noisiness when debugging
> Prepping for v3.2.0

- .github/workflows/main.yml
Ports over the basics to Actions, since Travis CI is deprecated.
> GitHub Actions CI Workflow

- test/assertions.rb
- test/client/cluster_test.rb
- test/client/multi_search_test.rb
- test/core_ext/time_test.rb
- test/test_helper.rb
Changes to ensure tests pass when run on ES 7 for:
- https://github.com/github/elastomer-client/blob/main/test/client/cluster_test.rb
- https://github.com/github/elastomer-client/blob/main/test/client/multi_search_test.rb
- https://github.com/github/elastomer-client/blob/main/test/core_ext/time_test.rb
> Fix cluster_test, multi_search_test and time_test

- .github/workflows/main.yml
> Test on ruby 3.2

- CHANGELOG.md
- lib/elastomer_client/version.rb
Update version to 5.1.0 since the changes involved are breaking and add a CHANGELOG entry
> Bump version to 5.1.0

- CHANGELOG.md
- lib/elastomer_client/version.rb
Update the version to 6.0.1, and make the corresponding change in CHANGELOG.md
> Update version and CHANGELOG.md

- .github/workflows/main.yml
- README.md
- docker/compose.yaml
- lib/elastomer_client/client/rest_api_spec/api_spec_v8_13.rb
- script/generate-rest-api-spec
- test/client/cluster_test.rb
- Generate rest API spec for 8.13 
- Upgrade CI from 8.7.0 to 8.13.0
- Upgrade ES version from 8.7.0 to 8.13.0
> Generate 8.13 rest api spec & update default ES8 version to 8.13

- lib/elastomer_client/client/rest_api_spec/api_spec_v8_17.rb
This PR adds the Elasticsearch 8.17 specification to the project.
> Adding Elastic 8.17 spec
